export default {
  AL: 'between 7 am and 7 pm',
  AK: 'between 7 am and 8pm',
  AZ: 'between 6 am and 7pm',
  AR: 'between 7:30 am and 7:30 pm',
  CA: 'between 7 am and 8 pm',
  CO: 'between 7 am and 7 pm',
  CT: 'between 6 am and 8 pm',
  DE: 'between 7 am and 8 pm',
  DC: 'between 7 am and 8 pm',
  FL: 'between 7 am and 7 pm',
  GA: 'between 7 am and 7 pm',
  HI: 'between 7 am and 6 pm',
  ID: 'between 8 am and 8 pm',
  IL: 'between 6 am and 7 pm',
  IN: 'between 6 am and 6 pm',
  IA: 'between 7 am and 9 pm',
  KS: 'between 7 am and 7 pm',
  KY: 'between 6 am and 6 pm',
  LA: 'between 6 am and 8 pm',
  ME: 'by 8 pm',
  MD: 'between 7 am and 8 pm',
  MA: 'between 7 am and 8 pm',
  MI: 'between 7 am and 8 pm', 
  MN: 'between 7 am and 8 pm',
  MS: 'between 7 am and 7 pm',
  MO: 'between 6 am and 7 pm',
  MT: 'between 7 am and 8 pm',
  NE: 'by 8 pm CST',
  NV: 'between 7 am and 7 pm',
  NH: 'between 7 am and 7 pm',
  NJ: 'between 6 am and 8 pm',
  NM: 'between 7 am and 7 pm',
  NY: 'between 6 am and 9 pm',
  NC: 'between 6:30 am and 7:30 pm',
  ND: 'between 7 am and 7 pm',
  OH: 'between 6:30 am and 7:30 pm',
  OK: 'between 7 am and 7 pm',
  PA: 'between 7 am and 8 pm',
  RI: 'between 7 am and 8 pm',
  SC: 'between 7 am and 7 pm',
  SD: 'between 7 am and 7 pm',
  TN: 'by 8 pm',
  TX: 'between 7 am and 7 pm',
  UT: 'between 7 am and 8 pm',
  VT: 'by 7 pm',
  VA: 'between 6 am and 7 pm',
  WV: 'between 6:30 am and 7:30 pm',
  WI: 'between 7 am and 8 pm',
  WY: 'between 7 am and 7 pm',
};