---
- name: Executive server provisioning
  hosts: all
  gather_facts: yes
  vars_files:
    - vars.yml
  roles:
    - role: common
      tags: common
    - role: letsencrypt
      when: ssl is defined and ssl == "yes"
      tags: letsencrypt
    - role: nginx
      tags: nginx
